### ISSUE TITLE
Primeros pasos

### ISSUE THREAD

**Issue by WuilfredoAz** [WuilfredoAz/Desafio-2#1]
Primeros pasos antes de comenzar con el repositorio formal del proyecto.

**Comment by TheWuilladors** [comment]
Ya se distribuyeron las responsabilidades. Quedaron de la siguiente manera:

**TheWuilladors:**
-_[Primeros pasos](https://github.com/TheWuilladors/Desafio-2/issues/1)_ 
-_[Sidebar Izquierdo](https://github.com/TheWuilladors/Desafio-2/issues/2)_
-_[Navegacion primaria](https://github.com/TheWuilladors/Desafio-2/issues/3)_
-_[Mejoras minimas en las categorias](https://github.com/TheWuilladors/Desafio-2/issues/4)_

**Test-Mk1:**
-_[Tarjetas de Post](https://github.com/TheWuilladors/Desafio-2/issues/5)_
-_[Documentacion](https://github.com/TheWuilladors/Desafio-2/issues/6)_
-_[Retoques en BLOG](https://github.com/TheWuilladors/Desafio-2/issues/7)_

**Comment by Test-mk1** [comment]
Ok. Ya estoy al tanto.
