### ISSUE TITLE
Sidebar Izquierdo

### ISSUE THREAD

**Issue by WuilfredoAz** [WuilfredoAz/Desafio-2#2]
Mejoras que se deben implementar al sidebar

**Comment by TheWuilladors** [comment]
Ya se terminó el desarrollo e implementación de los cambios mencionados en dicho issue. 

Resultados: 

**Commit ID:** [5e52acc4ba5dd981ba4f9bb6ccc01280b1a5844e ](https://github.com/TheWuilladors/Desafio-2/commit/5e52acc4ba5dd981ba4f9bb6ccc01280b1a5844e)
-_Nuevos textos en el sidebar_

**Commit ID:** [dc4624e111e682db4b56ef60c9c65a48f5515c40](https://github.com/TheWuilladors/Desafio-2/commit/dc4624e111e682db4b56ef60c9c65a48f5515c40)
-_Nuevo arte en el sidebar_

**Commit ID:** [a872d32eee978d003da67d3c0adc37ed94aa9ecd](https://github.com/TheWuilladors/Desafio-2/commit/a872d32eee978d003da67d3c0adc37ed94aa9ecd)
-_Nuevos estilos en las Redes Sociales del Sidebar _
