### ISSUE TITLE
Mejoras minimas en las categorias

### ISSUE THREAD

**Issue by WuilfredoAz** [WuilfredoAz/Desafio-2#4]
Mejoras minimas en el apartado visual de las categorias

**Comment by TheWuilladors** [comment]
Ya se termino de desarrollar este Issue.

Resultado:

**Commit ID:** [366d84757abf7a4cac57cb19219c900bd6a8f326](https://github.com/TheWuilladors/Desafio-2/commit/366d84757abf7a4cac57cb19219c900bd6a8f326)
-_Nuevos textos en los campos_
-_Nuevos estilos visuales_
