### ISSUE TITLE
Tarjetas de Post

### ISSUE THREAD

**Issue by WuilfredoAz** [WuilfredoAz/Desafio-2#5]
Generar nuevos estilos para los post

**Comment by Test-mk1** [comment]
Ya se trabajo dicho issue.

Resultado:

**Commit ID:** [f218af397c1d82bdb3ee800872de510586b4e5e1](https://github.com/TheWuilladors/Desafio-2/commit/f218af397c1d82bdb3ee800872de510586b4e5e1)
-_Nuevos estilos_
-_Nuevos estilos:hover_ 
-_Nuevos artes_

**Comment by TheWuilladors** [comment]
Ya lo revise. Todo esta perfecto.
