### ISSUE TITLE
Documentacion

### ISSUE THREAD

**Issue by WuilfredoAz** [WuilfredoAz/Desafio-2#6]
Generar lo necesario para cumplir con la documentación del proyecto

**Comment by Test-mk1** [comment]
Tuve que hacer un reset hard. Se me hizo un poco dificil aplicar un --amend 

Resultado

**Commit ID:** [46707646f131c52bede16a58267406192c726328](https://github.com/TheWuilladors/Desafio-2/commit/46707646f131c52bede16a58267406192c726328)

**Comment by TheWuilladors** [comment]
Vale, al menos pudiste efectuarlo exitosamente
