### ISSUE TITLE
Retoques en BLOG

### ISSUE THREAD

**Issue by WuilfredoAz** [WuilfredoAz/Desafio-2#7]
Enlazar archivos de estilos en Blog

**Comment by Test-mk1** [comment]
Ya se termino este issue.

Resultado

**Commit ID:** [87a8c905a21453e09c69a43e83f7818020a7f946](https://github.com/TheWuilladors/Desafio-2/commit/87a8c905a21453e09c69a43e83f7818020a7f946)

**Comment by TheWuilladors** [comment]
Perfecto ya lo integro al proyecto formal.
